# app/rag/claim_extractor.py

import json
import subprocess
import re
from typing import Dict, List

CLAIM_EXTRACTION_PROMPT = """
You are a claim extraction system.

Input:
- A single answer generated by an LLM.

Task:
- Decompose the answer into atomic, independently verifiable factual claims.

Rules:
1. Each claim must contain exactly ONE factual assertion.
2. Split compound or conjunctive sentences into multiple claims.
3. Preserve all numbers, dates, and named entities exactly.
4. Remove hedging, opinions, or vague language.
5. Do NOT add new information.
6. Do NOT explain reasoning.
7. Output MUST be valid JSON only.
8. If no factual claims exist, return an empty list.

STRICT OUTPUT FORMAT (no markdown, no explanation, no extra text):

{
  "claims": [
    {"id": "C1", "text": "..."},
    {"id": "C2", "text": "..."}
  ]
}

Answer:
"""

class ClaimExtractor:
    def __init__(self, model_name: str = "llama3.1:8b"):
        self.model_name = model_name

    def _call_llm(self, prompt: str) -> str:
        result = subprocess.run(
            ["ollama", "run", self.model_name],
            input=prompt,
            capture_output=True,
            text=True,
        )

        if result.returncode != 0:
            raise RuntimeError(result.stderr)

        return result.stdout.strip()

    def _extract_json_from_text(self, text: str) -> Dict:
        """
        Extract first valid JSON object from messy LLM output.
        """
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            pass

        # Remove markdown fences if present
        text = re.sub(r"```json|```", "", text)

        # Find first JSON object
        start = text.find("{")
        end = text.rfind("}")

        if start == -1 or end == -1:
            raise ValueError("No JSON object found in LLM output")

        cleaned = text[start:end + 1]
        return json.loads(cleaned)

    def extract_claims(self, answer: str) -> Dict[str, List[Dict[str, str]]]:
        full_prompt = CLAIM_EXTRACTION_PROMPT + answer

        try:
            raw_output = self._call_llm(full_prompt)

            # Debug line (can remove later)
            print("CLAIM RAW OUTPUT:", raw_output)

            parsed = self._extract_json_from_text(raw_output)

            if "claims" not in parsed or not isinstance(parsed["claims"], list):
                raise ValueError("Invalid claim schema returned")

            # Normalize IDs
            for i, claim in enumerate(parsed["claims"], start=1):
                claim["id"] = f"C{i}"

            return parsed

        except Exception as e:
            print("CLAIM EXTRACTION ERROR:", str(e))
            return {
                "claims": [],
                "error": f"claim_extraction_failed: {str(e)}"
            }

    def extract(self, answer: str) -> Dict[str, List[Dict[str, str]]]:
        return self.extract_claims(answer)
