CLAIM_EXTRACTION_PROMPT = """
You are a claim extraction system.

Input:
- A single answer generated by an LLM.

Task:
- Decompose the answer into atomic, independently verifiable factual claims.

Rules:
1. Each claim must contain exactly ONE factual assertion.
2. Split compound or conjunctive sentences into multiple claims.
3. Preserve all numbers, dates, and named entities exactly.
4. Remove hedging, opinions, or vague language.
5. Do NOT add new information.
6. Do NOT explain reasoning.
7. Output MUST be valid JSON only.
8. If no factual claims exist, return an empty list.

Output schema (STRICT):
{
  "claims": [
    {"id": "C1", "text": "..."},
    {"id": "C2", "text": "..."}
  ]
}

Answer:
"""
import json
import subprocess
from typing import Dict, Any, List


class ClaimExtractor:
    def __init__(self, model_name: str = "llama3"):
        self.model_name = model_name

    def _call_llm(self, prompt: str) -> str:
        """
        Calls Ollama locally. Single deterministic generation.
        """
        result = subprocess.run(
            ["ollama", "run", self.model_name],
            input=prompt,
            capture_output=True,
            text=True,
        )

        if result.returncode != 0:
            raise RuntimeError(result.stderr)

        return result.stdout.strip()

    def extract_claims(self, answer: str) -> Dict[str, List[Dict[str, str]]]:
        """
        Extract atomic claims from an answer.
        """
        full_prompt = CLAIM_EXTRACTION_PROMPT + answer

        try:
            raw_output = self._call_llm(full_prompt)

            # HARD JSON PARSE
            parsed = json.loads(raw_output)

            # SCHEMA GUARD
            if "claims" not in parsed or not isinstance(parsed["claims"], list):
                raise ValueError("Invalid claim schema")

            # ENFORCE ID FORMAT
            for i, claim in enumerate(parsed["claims"], start=1):
                claim["id"] = f"C{i}"

            return parsed

        except Exception as e:
            # Graceful degradation
            return {
                "claims": [],
                "error": f"claim_extraction_failed: {str(e)}"
            }
